spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_system
    username: booking_user
    password: booking_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
  cache:
    type: redis
    redis:
      time-to-live: 300000

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,cache

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html