spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking_system
    username: booking_user
    password: booking_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

  cache:
    type: redis
    redis:
      time-to-live: 300000
      cache-null-values: false

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,cache

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.cache: DEBUG
    com.lukianchykov.bookingsystem.service.CacheService: DEBUG
    com.lukianchykov.bookingsystem.service.UnitService: DEBUG